using System;
using System.IO;

class Program
{
    static void Main(string[] args)
    {
        Console.Write("Hello! What is your name? ");
        string na_userName = Console.ReadLine();
        na_Journal journal = new na_Journal(na_userName);
        bool na_menuFlag = true;
        while (na_menuFlag)
        {
            Console.WriteLine("");
            Console.Write($"Please select one of the following choices:\n1. Write\n2. Display\n3. Load\n4. Save\n5. Journal Statistics\n6. Quit\nWhat would you like to do? ");
            int na_menuChoice = int.Parse(Console.ReadLine());
            if (na_menuChoice == 1)
            {
                journal.na_AddEntry();
            }
            else if (na_menuChoice == 2)
            {
                journal.na_DisplayAll();
            }
            else if (na_menuChoice == 3)
            {
                journal.na_LoadFromCSV();
            }
            else if (na_menuChoice == 4)
            {
                journal.na_SaveToCSV();
            }
            else if (na_menuChoice == 5)
            {
                journal.na_journalStatistics();
            }
            else if (na_menuChoice == 6)
            {
                na_menuFlag = false;
            }
        }
    }
}

public class na_Entry
{
    public string na_Prompt { get; set; }
    public string na_Paper { get; set; }
    public string na_Date { get; set; }


    public na_Entry(string na_prompt, string na_paper)
    {
        na_Prompt = na_prompt;
        na_Paper = na_paper;
        DateTime theCurrentTime = DateTime.Now;
        na_Date = theCurrentTime.ToShortDateString();
    }
    public na_Entry(string na_prompt, string na_paper, string na_date)
    {
        na_Prompt = na_prompt;
        na_Paper = na_paper;
        na_Date = na_date;
    }

    public string na_display()
    {
        string na_rValue = $"Date: {na_Date} - Prompt: {na_Prompt}\n{na_Paper}";
        return na_rValue;
    }
}

public class na_Journal
{
    public List<na_Entry> na_Book;
    public string na_Author;
    private List<String> _na_promptList = new List<string>
    {
        "Who was the most interesting person I interacted with today?",
        "What was the best part of my day?",
        "How did I see the hand of the Lord in my life today?",
        "What was the strongest emotion I felt today?",
        "If I had one thing I could do over today, what would it be?",
        //The following prompts were generated by Gemini AI
        "Describe a smell that reminds you of childhood and explain where it takes you.",
        "If you could talk to yourself from five years ago for only one minute what would you say.",
        "List three things that made you smile today no matter how small they were.",
        "Imagine you are an object in your room right now and describe the world from that perspective.",
        "What is a habit you would like to start and why does it feel important to you.",
        "Write about a time you felt completely out of your element but learned something new.",
        "If you were given a key that could open any door in the world which door would you choose.",
        "Describe your perfect morning from the moment you wake up until noon.",
        "What is a piece of advice you often give others but struggle to follow yourself.",
        "Pick a song that currently resonates with you and explore the emotions it brings up."
    };

    public na_Journal(string na_name)
    {
        na_Book = new List<na_Entry>();
        na_Author = na_name;
    }

    public void na_AddEntry()
    {
        string na_prompt = na_GeneratePrompt();
        Console.WriteLine(na_prompt);
        string na_userPage = Console.ReadLine();
        na_Entry na_userEntry = new na_Entry(na_prompt, na_userPage);
        na_Book.Add(na_userEntry); 
    }
    public void na_DisplayAll()
    {
        Console.WriteLine("");
        foreach (na_Entry entry in na_Book) 
        {
            Console.WriteLine(entry.na_display());
        }
    }
    public void na_SaveToCSV()
    {
        //code from the code helps section of the assignment
        Console.Write("What is the filename? ");
        string filename = Console.ReadLine();

        using (StreamWriter outputFile = new StreamWriter(filename))
        {
            foreach (na_Entry na_entry in na_Book)
            {
                outputFile.WriteLine($"{na_entry.na_Prompt},~{na_entry.na_Paper},~{na_entry.na_Date}");
            }
        }
    }
    public void na_LoadFromCSV()
    {
        //Code from the code helps section of the assignment
        Console.Write("What is the filename? ");
        string filename = Console.ReadLine();

        if (File.Exists(filename))
        {
            string[] lines = File.ReadAllLines(filename);

            //Gemini suggested to clear the entry list before loading the filename
            na_Book.Clear();

            foreach (string line in lines)
            {
                string[] parts = line.Split(",~");

                string na_readPrompt = parts[0];
                string na_readPage = parts[1];
                string na_readDate = parts[2];

                na_Entry na_readEntry = new na_Entry(na_readPrompt, na_readPage, na_readDate);
                na_Book.Add(na_readEntry);
            }
        }
        else
        {
            Console.WriteLine("File not Found");
        }
    }
    
    public void na_journalStatistics()
    {
        int na_entryCount = na_Book.Count;
        int na_totalWords = 0;
        foreach (na_Entry entry in na_Book)
        {
            string[] words = entry.na_Paper.Split(' ');
            na_totalWords += words.Length;
        }
        double na_averageLength = na_totalWords / na_entryCount;
        Console.WriteLine($"You have made {na_entryCount} journal entries.");
        Console.WriteLine($"You have written {na_totalWords} words.");
        Console.WriteLine($"Each entry has an average length of {na_averageLength:F2} words.");
    }

    private string na_GeneratePrompt()
    {
        Random na_random = new Random();
        int random_Index = na_random.Next(0, _na_promptList.Count);
        String na_prompt = _na_promptList[random_Index];
        return na_prompt;
    }
}


